language: python
python: 3.6
env:
  - HUGO_VERSION=0.36

branches:
  only:
    - master

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/seisman/blog.seisman.info.git
  - cd blog.seisman.info
  - git submodule update --init --recursive --remote

install:
  # install latest hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  - pip install pygments

script:
  - ./hugo

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: ../blog.seisman.info/public
