language: node_js
node_js: "4"

sudo: required
dist: trusty
branches:
  only:
    - master

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/seisman/seisman.info.git
  - cd seisman.info
  - git submodule update --init --recursive --remote

install:
  # install the latest version of pandoc
  #- curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep 'browser_download_url.*deb' | awk '{print "wget", $2}' | sh
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-*-amd64.deb
  - npm install hexo gulp -g
  - npm install

script:
  - hexo generate
  - gulp

after_success:
  - git config --global user.name "Dongdong Tian"
  - git config --global user.email "seisman.info@gmail.com"
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo d --silent
