language: node_js
node_js: "4"

sudo: required
dist: trusty
branches:
  only:
    - master

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/seisman/seisman.info.git
  - cd seisman.info
  - git submodule update --init --recursive --remote

install:
  # install the latest version of pandoc
  - curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | grep 'browser_download_url.*deb' | awk '{print "wget", $2}' | sh
  - sudo dpkg -i pandoc-*-amd64.deb
  - npm install hexo gulp -g
  - npm install

script:
  - hexo generate --silent
  - gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
  on:
  branch: master
