language: python
python: 3.6
env:
  - HUGO_VERSIO=0.35

branches:
  only:
    - master

before_install:
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/seisman/seisman.info.git
  - cd seisman.info
  - git submodule update --init --recursive --remote

install:
  # install latest hugo
  - https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  - pip install pygments

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
